{
 "title": "Klipper speed monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"moonraker\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motion_report\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"live_velocity\")\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Time spent at 0 speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"moonraker\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motion_report\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"microseconds_since_last_zero\")\r\n  |> max()"
    }
   ]
  },
  {
   "title": "Time since last move",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "query": "from(bucket: \"moonraker\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motion_report\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"microseconds_since_last_zero\")"
    }
   ]
  },
  {
   "title": "Live speed",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"moonraker\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motion_report\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"live_velocity\")"
    }
   ]
  }
 ]
}